name: Python test

on:                             
  workflow_dispatch:              
  push:                          
    branches:
      - main
      - master        

jobs:                           
  tests:                          
    runs-on: ubuntu-latest         
    steps:                          
      - uses: actions/checkout@v3     
      
      - name: Print folder            
        run: |                        
          ls
      - name: Python installation 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install requirement
        run: |
          python -m pip install -r requirements.txt
      - name: lancement Pytest
        run: |
          python -m pytest
      - name: lancement pylint
        run: |
          python -m pylint application/

          